[update]GitHub Actionsで使うnodeのバージョンを18→20に変更
GitHub Actionsで以下のエラーが出たため、その対処としてバージョンを20に変更します。
------------------------------------------------------
Run npm run generate

> rss-generator@1.0.0 generate
> node src/index.js

/home/runner/work/rss-generator/rss-generator/node_modules/undici/lib/web/webidl/index.js:512
webidl.is.File = webidl.util.MakeTypeAssertion(File)
                                               ^

ReferenceError: File is not defined
    at Object.<anonymous> (/home/runner/work/rss-generator/rss-generator/node_modules/undici/lib/web/webidl/index.js:512:48)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/runner/work/rss-generator/rss-generator/node_modules/undici/lib/web/fetch/util.js:12:20)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)

Node.js v18.20.8
Error: Process completed with exit code 1.
------------------------------------------------------